<?php
namespace App\Http\Requests;

use App\Http\Requests\Request;
use App\Http\Controllers\CateController;

class CateRequest extends Request {

	/**
	 * Determine if the user is authorized to make this request.
	 *
	 * @return bool
	 */
	public function authorize()
	{
		return true;
	}

	/**
	 * Get the validation rules that apply to the request.
	 *
	 * @return array
	 */
	public function rules()
	{
		return [
			'txtCateName' => 'required|unique:categories,name',
			'txtOrder' => 'required',
			'txtKeywords' => 'required',
			'txtDes' => 'required',
//			'txtParent' => 'required'
		];
	}
	public function messages()
	{
		return [
			'txtCateName.required' => 'Nhập tên vào nhé',
			'txtCateName.unique' => 'Đã có tên trùng',
			'txtOrder.required' => 'Nhap order vao nhe',
			'txtKeywords.required' => 'Vui lòng nhập Keywords',
			'txtDes.required' => 'Nhập Des vào nhé',
//			'txtParent.required' => 'Nhập paren_id vào'
		];
	}
//	public function messages()
//	{
//		return parent::messages(); // TODO: Change the autogenerated stub
//	}

}
